### ISSUE TITLE
Aborted (core dumped) error

### ISSUE THREAD

**Issue by glample** [VKCOM/YouTokenToMe#58]
Hi. I'm trying YTTM for the first time, but I'm facing two issues:

I was trying to run the model on a relatively large file (100GB) but I was getting the following error:

```
reading file...
learning bpe...
number of unique characters in the training data: 14619
number of deleted characters: 0
number of unique characters left: 14619
Killed
```

Although I have 500GB of RAM. Is it normal for the model to use that much memory?

Afterwards, I tried to split the file into 2 and to learn the codes from 50GB of text. But now I get:

```
reading file...
learning bpe...
number of unique characters in the training data: 10359
number of deleted characters: 0
number of unique characters left: 10359
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```

Any ideas why?

Thanks

**Comment by xbelonogov** [comment]
Thank you for your feedback. It really dies because it doesn't have enough memory. 

If it was English text, then after decoding UTF-8 it takes 4 times more memory(and actually 5 because there is a moment when both representations exist)
Because of dynamic allocation, it could theoretically take twice more memory. So we get memory usage x10 of input size without doing anything useful. Other parts of the algorithm are not so memory consuming, but still they use a little bit. 

This situation can be improved. It is not really necessary to make explicit UTF-8 decoding. 

In practice, it's not very useful to train BPE on such a large corpus. I think you won't see a difference between corpus size equal to 5GB and 50GB.

**Comment by glample** [comment]
Thanks for your answer.

I agree that for English only 50GB does not make a big difference compared to 5GB, but in our case we are trying to learn codes over a large number of languages (> 100 languages) and in that setting we really need to learn the codes over a larger corpus.

We compared codes learned by fastBPE over 10GB vs 100GB of text, and we observed quite a difference there already.

**Comment by xbelonogov** [comment]
> We compared codes learned by fastBPE over 10GB vs 100GB of text, and we observed quite a difference there already.

Oh, that's interesting. 

I will try to fix that memory issue soon.

**Comment by xbelonogov** [comment]
The situation with memory usage turns out to be more complex. I made some improvements. For 1gb English text it now consumes 3 times less memory (4gb vs 12gb).
Could you check, does it help in your situation?

Thank you for raising this issue!
