### ISSUE TITLE
ska::flat_hash_map<uint64_t, uint64_t> real_pair_cnt;

### ISSUE THREAD

**Issue by jwijffels** [VKCOM/YouTokenToMe#8]
I've got a question related to this code:

https://github.com/VKCOM/YouTokenToMe/blob/e210a36bf2173522a1e30727f54fabe5faec2bad/youtokentome/cpp/bpe.cpp#L1058

Can you explain why is this 

`ska::flat_hash_map<uint64_t, uint64_t> real_pair_cnt;`

and not?

`ska::flat_hash_map<uint32_t, uint32_t> real_pair_cnt;`

**Comment by xbelonogov** [comment]
Key has type `int64_t` because this hashmap keeps  values from  function `int2comb` https://github.com/VKCOM/YouTokenToMe/blob/e210a36bf2173522a1e30727f54fabe5faec2bad/youtokentome/cpp/bpe.cpp#L101

Value has type `int64_t` because on relatively large dataset it's possible that number of  occurrence for specific pair of characters is bigger than 2^32

**Comment by jwijffels** [comment]
Later in the code at https://github.com/VKCOM/YouTokenToMe/blob/e210a36bf2173522a1e30727f54fabe5faec2bad/youtokentome/cpp/bpe.cpp#L1069
where you push a MergeCandidate https://github.com/VKCOM/YouTokenToMe/blob/e210a36bf2173522a1e30727f54fabe5faec2bad/youtokentome/cpp/bpe.cpp#L105
it looks like it is uint32_t and not uint64_t
Am I misinterpreting this?

**Comment by xbelonogov** [comment]
`x.second` is 64 bit integer it goes to `count` from `MergeCandidate`. `count` has type `size_t`, so it's also 64 bit integer. I think everything is correct here.

**Comment by jwijffels** [comment]
you're right, so why not put MergeCandidate count then of type uint64_t?
